apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: "{{ .Values.productName }}-auth-role"
        vault.hashicorp.com/agent-inject-secret-mongodb.json: "mongodb/creds/{{ .Values.productName }}-{{ .Values.nodeEnv }}"
        vault.hashicorp.com/agent-inject-template-mongodb.json: |
          {{- with secret "mongodb/creds/demo-lab-staging" -}}
          {
            "username": "{{ .Data.username }}",
            "password": "{{ .Data.password }}"
          }
          {{- end }}
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.version }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        env:
        - name: OPENTRACING_JAEGER_SERVICE_NAME
          value: marketsummary.{{ .Release.Namespace }}
        - name: NODE_ENV
          value: {{ .Values.nodeEnv }}
        - name: DATABASE_NAMESPACE
          value: {{ .Values.productName }}-db
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
